### ISSUE TITLE
ObjectPutBytes body length error

### ISSUE THREAD

**Issue by wI2L** [ncw/swift#111]
I have noticed that, time to times I get this kind of error when I try so save an object using `ObjectPutBytes`:

```
Put <url> : http: ContentLength=xxxx with Body length 0
```
I think the watchdog timer may be responsible of this.

Any idea ?

**Comment by ncw** [comment]
What that looks like is something closed the connection before any of the body had been transferred.

If it was the watchdog then you'd get a different error (I haven't got an example to hand).

I suspect it is probably your provider, but if you want to know for certain then you'll have to use wireshark and see who closes the TCP socket.
