### ISSUE TITLE
ObjectNamesAll ignores Marker

### ISSUE THREAD

**Issue by rivo** [ncw/swift#113]
I'm doing a range request with `ObjectNamesAll()` with the `Marker` and `EndMarker` parameters. (The result could be quite large so I'm using the "All" version.) Unfortunately, the `Marker` parameter I'm providing is ignored. It's reset to an empty string [here](https://github.com/ncw/swift/blob/b2a7479cf26fa841ff90dd932d0221cb5c50782d/swift.go#L1082) so I'm getting too many object names.

Unless I'm misunderstanding the purpose of the `ObjectNamesAll()` function, this seems like a bug to me. I believe the `Marker` parameter should be left unchanged for the first request. Or is there a specific reason it is cleared?

**Comment by ncw** [comment]
Sorry for the delay in replying...

The `All` versions are supposed to page through and return everything hence the overwriting of `Marker` and `Limit`.

I see the logic in your proposal.  However making this change would break programs which have set the `Marker` in the `ObjectsOpts` already.  This is probably unlikely.  However I really don't want to break any of [the existing users](https://godoc.org/github.com/ncw/swift?importers).

So the safe thing to do would be to make a differently named function which works as you wish.

Or maybe do a code review on the existing users and check the usage.  I checked rclone and it would be OK with the change.

Thoughts?

**Comment by rivo** [comment]
Sorry for the late reply from my side, too. ;-)

While I still think it would be useful to have such a function (I would probably prefer an extra function so as not to break existing systems), I currently don't have the budget to implement this myself. And it seems that we're fine without it, for now.

If this becomes a problem in our project, they may get in touch again. But for now, I'll close this issue. Thanks for your help, though.

**Comment by ncw** [comment]
Thanks for your reply :-)
