### ISSUE TITLE
Test failure on armv7hl

### ISSUE THREAD

**Issue by eclipseo** [ncw/swift#117]
Fedora Rawhide + Go 1.11.1 + ncw/swift v1.0.41, on armv7hl only:
```
Testing: github.com/ncw/swift
Testing: "/builddir/build/BUILD/swift-1.0.41/_build/src/github.com/ncw/swift"
+ GOPATH=/builddir/build/BUILD/swift-1.0.41/_build:/usr/share/gocode
+ go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\'''
Waiting for server to start . Started
--- FAIL: TestWatchdogReaderOnSlowNetwork (0.24s)
    watchdog_reader_test.go:53: Timer should not have fired
FAIL
exit status 1
FAIL	github.com/ncw/swift	3.316s
```

**Comment by ncw** [comment]
Does it fail every time?

I think that test has always been unreliable!  It uses timers, whereas it should be using some proper concurrency primitives.

Fancy sending a PR to fix it up?

**Comment by eclipseo** [comment]
> Does it fail every time?
> 
I rerun the build and apparently it works now: https://koji.fedoraproject.org/koji/taskinfo?taskID=30171266
Sorry for the noise.

**Comment by ncw** [comment]
No worries!
