### ISSUE TITLE
MaxIdleConnsPerHost

### ISSUE THREAD

**Issue by omarali** [ncw/swift#120]
Why is MaxIdleConnsPerHost set to such a high number (2048) by default?

**Comment by ncw** [comment]
A good question... Not sure of the answer!

Is it causing you a problem?

Maybe send a PR to reduce it?

**Comment by omarali** [comment]
Yes, it is causing "too many files open" errors. I'm going to send a PR to change it to 512 which is half of linux's default open files limit of 1024.

**Comment by ncw** [comment]
This is fixed in  6f342da371d063863f2f354f183e4ab0ef72d287 - thank you :-)
