### ISSUE TITLE
Bulk-delete support in test swift-server

### ISSUE THREAD

**Issue by Akhilachatlapalle** [ncw/swift#135]
This is more of seeking help instead of an issue.
Is there a way to enable bulk-delete support in the test swift-server(https://github.com/ncw/swift/blob/master/swifttest/server.go#L1062). Tried adding this snippet under Info `,
			"bulk_delete": map[string]interface{}{
				"max_failed_deletes" : 1000,
				"max_deletes_per_request": 1000,
				"max_containers_per_extraction": 1000,
				"max_failed_extractions": 1000,
			}`. Anyways I also need a handler doing this stuff internally. I wonder if anyone already had the implementation ?!

**Comment by ncw** [comment]
I think it would need a patch.

Do you want to contribute one?

**Comment by Akhilachatlapalle** [comment]
Sure, I will do it :)
