### ISSUE TITLE
Ability to silence logs about multiple header values

### ISSUE THREAD

**Issue by tino** [ncw/swift#36]
I get this line printed multiple times per second:
```
swift: received multiple values for header "Accept-Ranges"
```
from: https://github.com/ncw/swift/blob/master/swift.go#L202

(while using rclone). This makes the output completely unusable, and there is nothing that I can do to fix it, so it is quite a useless warning to me. Would there be any way to silence it?

**Comment by ncw** [comment]
Interesting - which swift are you using?

I think that message can go - it is really only for debugging.

**Comment by tino** [comment]
That would be nice. Or only showing it when verbose=true maybe? I use: http://www.cloudvps.com/openstack/object-store/

**Comment by ncw** [comment]
Thanks for your bug report!
