### ISSUE TITLE
cannot parse time

### ISSUE THREAD

**Issue by vtolstov** [ncw/swift#37]
i have old version of swift and can't get ObjectGet because of error:
```
parsing time "" as "Mon, 02 Jan 2006 15:04:05 GMT": cannot parse "" as "Mon"
```
as i understand default TimeFormat does not equal of my output, how can i deal with this?

**Comment by ncw** [comment]
It appears that your server is not providing the `Last-Modified` on a `HEAD` at all. It isn't the wrong format, it just isn't present.

Which version of swift are you using, and are you using any proxy / caching layers in front of it?

I'm not aware of any version of swift which doesn't provide `Last-Modified` so I'd suspect this is a problem with a proxy.

You could work around this by using the `Objects` call instead.  I'd consider a patch to skip the `Last-Modified` parsing if it isn't present too.

**Comment by vtolstov** [comment]
i found problem - this message appeared than i provide invalid object path, swift says 204 No Content, but this packages ignores this error and try to parse data.

**Comment by ncw** [comment]
204 isn't an error, it is the normal return code for this call.

I did a few tests to try to reproduce this with invalid object paths, but all I get back are 404 errors.  Can you provide a reproduction of the problem?

Thanks

**Comment by vtolstov** [comment]
@ncw Now i can't, but if i can find it again - i'm try to send detailed report. Thanks!

**Comment by ncw** [comment]
OK thanks - send that report if you can get it repeatable!
