### ISSUE TITLE
Identity v3 AUTH support

### ISSUE THREAD

**Issue by stenstad** [ncw/swift#38]
Hi, with the 2.2 (Juno) release of Swift it finally supports Identity v3 support. Would it be possible to extend the existing AUTH system to support this?

V3 support was recently added to Gophercloud as well, so pointers on how to implement this should be easily accessible.

https://github.com/rackspace/gophercloud/tree/master/openstack/identity/v3

**Comment by ojacques** [comment]
I'm interested in this as well. @lebauce, was KeyStone v3 in ncw/swift anywhere on your radar?
/cc @nevermosby

**Comment by daihaojun** [comment]
@ojacques @lebauce @nevermosby created a new pull request for this  issue https://github.com/ncw/swift/pull/42

**Comment by ncw** [comment]
I've merged @daihaojun code to implement this.  I haven't got a v3 openstack to test it against so I would appreciate you having a go with it!  if you find any problems then please open another issue.

Thanks

Nick
