### ISSUE TITLE
ObjectPut with null byte file

### ISSUE THREAD

**Issue by vtolstov** [ncw/swift#39]
I have some empty files, when i try to put it to swift i get errors like:
Put http://TTTTT:80/v1/XXXXXXXXX/public/file18: EOF

this is expected like EOF error, becasue file body is empty, but how can i deal with error in function?
I can't check file size before put, because i have only io.Reader.

**Comment by ncw** [comment]
Which swift system are you using?

I'd be surprised if there was a problem with empty files - I've tested that lots in the past.

Can you try the unit tests against your swift server?

```
cd $GOPATH/src/github.com/ncw/swift
export SWIFT_TENANT='tenant'
export SWIFT_API_USER='user'
export SWIFT_API_KEY='pass'
export SWIFT_AUTH_URL='https://provider/v2.0'
go test -v
```

**Comment by vtolstov** [comment]
I have swift diablo release
log for go test -v https://gist.github.com/vtolstov/40bbafca4605fba79c1b

**Comment by ncw** [comment]
Thanks for that.

I'm not sure whether the swift module will work with Diablo - I think I started with Essex originally.

I don't think the basic API has changed though.

Looking at your log I wonder if there is a proxy between you and the swift server which is causing problems?

**Comment by vtolstov** [comment]
Yes, i have a proxy - nginx. What i need to check on it to detect my issue, do you know or have suggestions?

**Comment by ncw** [comment]
Can you run the unit tests without the proxy? That would at least narrow it down.

**Comment by ncw** [comment]
I'm going to close this now as it has been open a long time without me being able to reproduce the problem.

If you can find a way to reproduce it for me, then please re-open.

Thanks

Nick
