### ISSUE TITLE
not able to specify/connect to a specific project through v3 auth

### ISSUE THREAD

**Issue by nishtha-srivastava** [ncw/swift#55]
Hi.
I am working on an OpenStack landscape in which there are many projects in the same domain.
I am using v3 auth endpoint.
While creating connection, there is no field to specify project/tenant (for v3 auth).

// Create a connection
    c := swift.Connection {
        UserName: username,
        ApiKey: apikey,
        AuthUrl: authurl,
        Domain: domain, // Name of the domain (v3 auth only)
        AuthVersion: 3,
        //Tenant:   tenant,  // Name of the tenant (v2 auth only)
        //ProjectId: projectid,
    }

By default, its connecting to the first project in the domain.
However, I am not able to connect to my desired project in the domain.

**Comment by ncw** [comment]
If you look at [the docs for the Connection struct](https://godoc.org/github.com/ncw/swift#Connection) you'll see there is space for a `Tenant` or `TenantId` - that should be what you need.  A tenant and project are the same things in Openstack-speak and these are put in for v3 auth.

I think if anything is wrong it is the docs for `Tentant` and `TenantId` which should say (v2,v3 auth only) probbly.

Let me know if that works for you and I'll change the docs!

**Comment by nishtha-srivastava** [comment]
Hi,
Sorry for replying late.
It had worked for me !
Thanks.

**Comment by ncw** [comment]
@nishtha-srivastava thanks for the update
