### ISSUE TITLE
OVH endpoint

### ISSUE THREAD

**Issue by xlucas** [ncw/swift#60]
Would it be possible to add OVH's authentication endpoint (`https://auth.cloud.ovh.net/v2.0`) in the set of URLs proposed when generating a remote's configuration for Swift ?

**Comment by ncw** [comment]
Sure.  Fancy making a pull request?

**Comment by ncw** [comment]
Actually I think this issue should probably be on the rclone issue tracker?

**Comment by xlucas** [comment]
Indeed, that's related to rclone.
I'm gonna open a pull request for this, thanks !
