### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by fd0** [ncw/swift#93]
For [restic](https://github.com/restic/restic), we'll switch to `dep` shortly, and it would be very helpful if you could tag a release. Thanks!

https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by ncw** [comment]
@cezarsa and I have been discussing this.

The swift library is a continuous release model with master always production ready, so what we need is some automation to automatically do tagging - do you know of anything that could help here?

If we start doing tagging manually, we'll forget to update the tags and they everyone's versions will get old!

**Comment by fd0** [comment]
I'm not aware of any automated helper. Having master always production ready is obviously a big plus :)
I'm not sure if that add so much value, but you could then also have release schedule based on time.

**Comment by cezarsa** [comment]
Yeah, I agree that time based releases might be the right answer here. It avoids the clutter of possibly too many releases (one for every commit) and also the need to make arbitrary decisions on when a new feature/fix is worth a new release if not tagging every commit.

If we go for something like one release every month (if there was any activity on that month) I don't think too much automation is necessary. Maybe just a script updating a `Version` constant and calling `git tag`. Manually running such script give us a last chance to review if there's something dangerous on the release. I could set up a calendar reminder to do this once a month. :)

Decisions need to be made on which versioning scheme to use and what's the initial version. SemVer  seem like an obvious choice here but it introduces the need to make a decision on each release on whether we'll update the Minor or the Patch component (assuming we don't break compatibility). 

Docker recently moved away from SemVer to a time based versioning scheme (v<Year>.<Month>.<Patch>) similar to Ubuntu releases. I'll admit that I'm not a big fan of such scheme and would rather we stick with SemVer, it should be fairly straightforward to decide between updating Minor or Patch on each release.

Regarding initial version I'd say `v1.0.0` is a good start. :) Thoughts?

**Comment by fd0** [comment]
I agree, semver is not perfect but a common choice. First version 1.0.0 sounds good!

**Comment by fd0** [comment]
From my point of view, semver has the nice property of being able to communicate breaking changes in a machine-readable way. And there's really no shame in having version `24.18.3`, for the 23rd breaking change. The only difference to not having releases at all, or time-based releases like Docker, is being able to communicate a breaking change.

You can even have a small program that checks that all types, functions, methods, variables and constants exported by the last release are still exported and have the same types/signatures. If this is the case, increment the minor version for the next release, otherwise increment the major version.

**Comment by fd0** [comment]
Soo, any progress on the release tag front? :)

**Comment by calvernaz** [comment]
if no decision has been made, could we just tag the current master with a version and change it later? From dep perspective doesn't make a difference, right?

**Comment by ncw** [comment]
I have been through and tagged historical releases approximately every month.

I've found a nice little tool https://github.com/calmh/git-autotag we can use for tagging going forward.

The policy should be to tag changes when we know they are stable.
